name: Deploy simulator
on:
  pull_request:

jobs:
  deploy-simulator:
    runs-on: wxm_playground_ec2
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup smart contracts
        run: ./setup-smart-contracts.sh
      - name: Start services
        run: docker-compose up -d
        