version: '3.3'
services:
  hardhat-node:
    build: 
      target: hardhat
      dockerfile: ./Dockerfile
    container_name: hardhat-node
    network_mode: "host"
  frontend-node:
    build:
      target: frontend
      dockerfile: ./Dockerfile
    container_name: frontend-node
    depends_on:
      - "hardhat-node"
    network_mode: "host"
