name: Deploy simulator
on:
  pull_request:

jobs:
  deploy-simulator:
    runs-on: wxm_backend_pg
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup smart contracts
        run: ./setup-smart-contracts.sh
      - name: Stop running containers 
        run: docker-compose down --remove-orphans
      - name: Start services
        run: docker-compose up -d --build --force-recreate
        